
#Rolling updates
new kubernetes object : Deployment


/////
apiVersion: apps/v1
kind: Deployment
metadata:



spec:

////////


apiVersion: v1
kind: Deployment
metadata:
    name: myapp-deployment
    labels:
        app: myapp
        type: front-end

spec:
    template:  ---> from Pod 

        metadata:
        name: nginx
        labels:
            app: nginx
            tier: frontend

        spec:
        containers:
        - name: nginx
            image: nginx        
    
    replicas: 3
    selector:
        matchLabels:
            type: front-end


////////

Its same as ReplicationController or ReplicaSet only different is in kind: Deployment a k8s object

commands:

kubectl cerate -f deployment-def.yaml
kubectl get deployments
kubectl get replicaset
kubectl get pods

kubectl get all 

/////


Using kubectl Run command:


# create pod
kubectl run nginx --image=nginx

#Generate POD Manifest YAML file (-o yaml). Don’t create it(–dry-run)
kubectl run nginx --image=nginx --dry-run=client -o yaml

#Create deployment
kubectl create deployment --image=nginx nginx

#Generate Deployment YAML file (-o yaml). Don’t create it(–dry-run)
kubectl create deployment --image=nginx nginx --dry-run=client -o yaml

#Generate Deployment YAML file (-o yaml). Don’t create it(–dry-run) and save it to a file.
kubectl create deployment --image=nginx nginx --dry-run=client -o yaml > nginx-deployment.yaml

kubectl create -f nginx-deployment.yaml


in k8s version 1.19+ , replicas option is availbele

kubectl create deployment --image=nginx nginx --replicas=4 --dry-run=client -o yaml


/////
