
Secret 

to store senstive data 


Cerate secret
Inject into the pod 


kubectl create secret generic app-secret \
--from-literal=DB_Host=mysql \
--from-literal=DB_User=root \
--from-literal=DB_Password=password \


kubectl create secret generic <secret-name> \
--from-file=<path-to-file>



cereat secret-definition.yaml 

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_Host: use here encoded data
  DB_User: use here encoded data
  DB_Password: use here encoded data


k get secrets 
k describe secrets 
k get secret app-secret -o yaml 

baseecnode64 for encode data 

echo -n "hellopassword" | base64 --encode 

echo -n "cmqwe3-=" | base64 --decode 


apiVersion: v1
kind: Pod
metadata: 
  name: simple-pod 
spec:
  containers:
  - name: simple-conatiner1
    image: image-conatiner1
    ports:
      - containerPort:  8080
    envFrom:
      - secretRef:
          name: app-secret

k create -f pod-def.yaml 

////////////////////////

controlplane ~ ➜  k get secrets
NAME              TYPE                                  DATA   AGE
dashboard-token   kubernetes.io/service-account-token   3      25s


k describe secrets dashboard-token

check Data section here 

controlplane ~ ➜  k describe secrets dashboard-token | grep Type
Type:  kubernetes.io/service-account-token



controlplane ~ ➜  k create secret generic  db-secret \
> --from-literal=DB_Host=sql01 \
> --from-literal=DB_User=root \
> --from-literal=DB_Password=password123 
secret/db-secret created


controlplane ~ ➜  k edit pod webapp-pod 
error: pods "webapp-pod" is invalid
A copy of your changes has been stored to "/tmp/kubectl-edit-715060136.yaml"
error: Edit cancelled, no valid changes were saved.


controlplane ~ ➜  k replace --force -f /tmp/kubectl-edit-715060136.yaml
pod "webapp-pod" deleted
pod/webapp-pod replaced


    envFrom:
    - secretRef:
        name: db-secret



as secret is encoded ,anyone can decode base64 hence use external seceret store:

1. Vault - HashiCrop
2. AWS secret manager 
3. Secret Manager - gcp 
4. key - azure 

kubectl exec -it nameofpod -- bash


Secret Store CSI Driver Tutorial | Kubernetes Secrets | AWS Secrets Manager 

